<?php include('header.php');?>

  <!-- start page content -->

    <main class="container-fluid">

        <div class="jumbotron text-center dep3 ">
            Polymer Biotechnology
        </div>

        <!-- sticky sidebar -->
        <div class="row">
  			<div class="col-md-3" id="leftCol">

              	<ul class="nav nav-stacked" id="sidebar">
                    <li>
                        <a href="#sec0">DESCRIPTION</a>
                    </li>
                    <li>
                        <a href="#sec1">MEMBERS</a>
                    </li>
                    <li>
                        <a href="#sec2">PROJECTS</a>
                    </li>
                    <li>
                        <a href="#sec3">PUBLICATIONS</a>
                    </li>
                    <li>
                        <a href="#sec4">FUNDING</a>
                    </li>
              	</ul>

      		</div>

            <!-- Page content -->
            <div class="col-md-9">

                <div id="sec0" class="row margin-bottom-3">
                    <div class="col-md-12 top-link">
                        <a href="index.php">Home</a>
                        <a href="research.php"> | Research</a>
                        <a href="research.php"> | Departments</a>
                        <a href="environmental_biology.php" style="color: #b6d017;"> | Environmental Biology</a>
                        <a href="#" style="color: #b6d017;"> | Polymer Biotechnology </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p>
                            The problem of environmental pollution generated by the massive use of plastic materials derived from the petrochemical industry has attracted much interest in the implementation of sustainable processes, involving the use of biomass derived from waste to generate alternative materials (bioplastics) to these high consumption products. Many of our research activities focus on the production of bacterial polyesters or polyhydroxyalkanoates (PHA), which are considered one of the most promising bioplastics due to their biodegradable character. Our designs are based on the use of industrial and urban biowastes such as glycerol, fatty residues or synthetic gas (syngas) as sources for the bacterial fermentation. Both natural-producing bacteria, such as Pseudomonas putida and Rhodospirillum rubrum, as well as genetically optimized microorganisms, are considered in these processes. We invest our effort in studying  the metabolic and regulatory networks in producing microorganisms and others sharing their natural environment such as predatory bacteria  like Bdellovibrio bacteriovorus. We apply our findings in the production of  new materials including the second generation functionalized PHA with new properties (e.g. anti-microbial), and susceptible to chemical modification after its biosynthesis. In addition, we are very interested in the design and development of new downstream systems to process the bacterial biomass for the separation of intracellular bioproducts. In this aspect, we use different strategies to control the release of bioproducts to the extracellular medium as controlled self-cell-disruption systems based on the production of  lytic proteins in the producer microorganism. Finally, we are working on the identification and characterization of enzymes for synthesis and biodegradation of materials, as well as the production of building blocks as monomers for polymer synthesis.
                        </p>
                    </div>
                </div>

                <div class="row margin-top-5 scientific-report">
                    <a href="http://www.cib.csic.es/Memo/grupos/76.pdf" target="_blank">
                        <img src="img/folder.svg" alt=""/>
                    </a>
                    <span style="margin-left:10px;">Last Team's Scientific Report</span>
                </div>

                <div id="sec1" class="row section-title margin-top-3">
                    <div class="col-md-12">
                        <span class="marker" style="background-color: #b6d017;"></span>
                        <span>MEMBERS</span>
                    </div>
                </div>
                <div class="row members margin-top-2">
                    <div class="col-md-12">
                        <div class="col-md-6 boss">
                            <div>
                                <a href="caballero.php">
                                    <img src="img/aux_prieto.png" alt="" class="img-responsive" style="height:70px;" />
                                </a>
                            </div>
                            <div>
                                <div class="title">
                                    Head of Lab
                                </div>
                                <div class="subtitle">
                                    Prieto Jiménez, María Auxiliadora
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row margin-top-6">
                    <div class="col-md-12">
                        <div class="col-md-6 staff">
                            <div class="title">
                                Scientific Staff
                            </div>
                            <div class="subtitle">
                                <ul>
                                    <li>Prieto Jiménez, María Auxiliadora</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 staff">
                            <div class="title">
                                Technical Staff
                            </div>
                            <div>
                                <ul class="subtitle">
                                    <li>Hernández Arriaga, Ana María</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row margin-top-6">
                    <div class="col-md-12">
                        <div class="col-md-6 staff">
                            <div class="title">
                                Postdoctorals
                            </div>
                            <div class="subtitle">
                                <ul>
                                    <li>Gonzalez Alvarez, Erika</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 staff">
                            <div class="title">
                                Graduate Students
                            </div>
                            <div>
                                <ul class="subtitle">
                                    <li>Tarazona Lizcano, Natalia Andrea</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row margin-top-6">
                    <div class="col-md-12">
                        <div class="col-md-6 staff">
                            <div class="title">
                                Postgraduates
                            </div>
                            <div class="subtitle">
                                <ul>
                                    <li>González Ximénez de Embún, Miguel</li>
                                    <li>Guillem Amat, Ana</li>
                                    <li>Navas Jiménez, Carolina</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-6 staff">
                            <div class="title">
                                Visiting Scientists
                            </div>
                            <div class="subtitle">
                                <ul>
                                    <li>Alameda Martin, Aitor</li>
                                    <li>Sanjuan Sanchez, Alberto</li>
                                    <li>Santamaría Fernández, María Estrella</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>



                <div class="row">
                    <div class="col-md-12">
                        <img class="img-responsive" src="img/polymer_biotech_group.jpg" style="width:100%;"/>
                    </div>
                </div>

                <div id="sec2" class="row section-title">
                    <div class="col-md-12">
                        <span class="marker" style="background-color: #b6d017;"></span>
                        <span>PROJECTS</span>
                    </div>
                </div>
                <a href="#">
                    <div class="row margin-top-1 service-item">
                        <div class="colo-md-12" style="margin-left:10px;">
                            Sustainable use of transgenic maize (Bt-maize)
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="row margin-top-1 service-item">
                        <div class="colo-md-12" style="margin-left:10px;">
                            Insecticide resistance in the Mediterranean fruit fly
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="row margin-top-1 service-item">
                        <div class="colo-md-12" style="margin-left:10px;">
                            Combined effects of abiotic (drought) and biotic (mites) stress on crop damage.
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="row margin-top-1 service-item">
                        <div class="colo-md-12" style="margin-left:10px;">
                            Studies on the physiology and molecular biology of allergy producing mites
                        </div>
                    </div>
                </a>


                <div id="sec3" class="row section-title">
                    <div class="col-md-12">
                        <span class="marker" style="background-color: #b6d017;"></span>
                        <span>PUBLICATIONS</span>
                    </div>
                </div>
                <div class="row margin-top-3 publication">
                    <a href="#">
                        <img src="img/folder.svg" alt=""/>
                    </a>
                    <div style="margin-left:10px;">
                        <strong style="color:red;">under construction</strong>
                    </div>
                </div>




                <div id="sec4" class="row section-title margin-bottom-3">
                    <div class="col-md-12">
                        <span class="marker" style="background-color: #b6d017;"></span>
                        <span>FUNDING</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                            <li>MICINN, AGL2009-08813</li>
                            <li>MICINN, AGL2010-21349-C02-01/AGR</li>
                            <li>MINECO, AGL2012-34289</li>
                            <li>MINECO, AGL2013-42632-R</li>
                            <li>JPI- FACCE Era Net Plus - Genomite</li>
                            <li>Monsanto Europe S.A.</li>
                            <li>ALK-Abelló</li>
                            <li>Cheminova A/S</li>
                        </ul>
                    </div>
                </div>
                <div class="row margin-top-5">
                    <div class="col-md-12">
                        <span class="input-group-btn">
                            <a href="environmental_biology.php">
                                <button class="btn btn-default button-secondary" type="submit">Back</button>
                            </a>
                        </span>
                    </div>
                </div>

            </div>

        </div>

    </main>

<?php include('footer.php');?>
    <!-- JS Imports -->
    <script src="js/vendor/jquery-1.11.2.min.js"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script src="js/vendor/jquery-ui.js"></script>
    <script src="js/app.js"></script>
